### ISSUE TITLE
Kurser för skratch

### ISSUE THREAD

**Issue by tradfursten** [hlaueriksson/programmering-for-barn#2]
Jag tycker att Internetstiftelsens kurser i skratch
https://youtube.com/playlist?list=PLtDs7N_g_eiZGpEmFKf946HuJZ9a7TNuS
Och
https://youtube.com/playlist?list=PLtDs7N_g_eiaK8N07W9iQdHin45q6UpOP

**Comment by hlaueriksson** [comment]
Tack för tipset!

Det är dessa som ingår i kurserna från [Digitala lektioner](https://github.com/hlaueriksson/programmering-for-barn#:~:text=t%C3%A4nkande%20och%20probleml%C3%B6sning.-,Digitala%20lektioner,-%2D%20Vad%20%C3%A4r%20en) som finns som länk, eller hur?

**Comment by tradfursten** [comment]
Perfekt, missade det
